CREATE TABLE [dbo].[StudentAdmission] (
    [AdminNo]          INT            IDENTITY (1, 1) NOT NULL,
    [DOJ]              DATE           NULL,
    [FirstName]        NVARCHAR (50)  NULL,
    [LastName]         NVARCHAR (50)  NULL,
    [FName]            NVARCHAR (50)  NULL,
    [MName]            NVARCHAR (50)  NULL,
    [DOB]              DATE           NULL,
    [Gender]           NCHAR (10)     NULL,
    [Religion]         NVARCHAR (50)  NULL,
    [Category]         NVARCHAR (50)  NULL,
    [PermanentAddress] NVARCHAR (150) NULL,
    [PDistrict]        NVARCHAR (100) NULL,
    [Contact1]         BIGINT         NULL,
    [LocalAddress]     NVARCHAR (150) NULL,
    [LDistrict]        NVARCHAR (100) NULL,
    [Contact2]         BIGINT         NULL,
    [Sib1AdminNo]      INT            NULL,
    [Sib2AdminNo]      INT            NULL,
    [Class]            NCHAR (10)     NULL,
    [Section]          NCHAR (10)     NULL,
    [PSchoolName]      NVARCHAR (100) NULL,
    [LClass]           NCHAR (10)     NULL,
    [YOPLC]            DATE           NULL,
    [LCMarks]          INT            NULL,
    [Medium]           VARCHAR (50)   NULL,
    [DocID]            INT            NULL,
    [AdmissionFee]     INT            NULL,
    [HostelAdminFee]   INT            NULL,
    [TieBeltCharge]    INT            NULL,
    [OtherCharges]     INT            NULL,
    [Rebate]           INT            NULL,
    [RemarkRebat]      NVARCHAR (150) NULL,
    [StudentRemark]    NVARCHAR (200) NULL,
    [Photo]            IMAGE          NULL,
    [EnteredBy]        NVARCHAR (80)  NULL,
    [EnteredOn]        DATE           NULL,
    [UpdatedBy]        NVARCHAR (80)  NULL,
    [UpdatedOn]        DATE           NULL,
    CONSTRAINT [PK_StudentAdmission] PRIMARY KEY CLUSTERED ([AdminNo] ASC),
    CONSTRAINT [FK_StudentAdmission_StudentAdmission] FOREIGN KEY ([Sib1AdminNo]) REFERENCES [dbo].[StudentAdmission] ([AdminNo]),
    CONSTRAINT [FK_StudentAdmission_StudentAdmission1] FOREIGN KEY ([Sib2AdminNo]) REFERENCES [dbo].[StudentAdmission] ([AdminNo])
);

